package com.zhang2014.project.syntactical;

public enum Token
{
  SELECT, DISTINCT, WITH, TOTALS, FROM, ON, USING, LEFT, INNER, ARRAY, JOIN, COMMA_STR, UNSPECIFIED, GLOBAL, LOCAL, ANY,
  ALL, RIGHT, FULL, CROSS, OUTER, FINAL, UNION, WHERE, PREWHERE, GROUP, BY, SETTINGS, HAVING, AS, NOT, IS, NULL, BETWEEN, CAST, WHEN, THEN, CASE, ELSE, END, OR, AND, ORDER, FIRST, LAST, ASCENDING, DESCENDING, ASC, DESC, COLLATE,LIMIT;
}
